#!/usr/bin/env ruby
forge 'https://forgeapi.puppetlabs.com'

metadata

mod 'cmc-core',
  :git => 'git@ssh.dev.azure.com:v3/ConclusionMC/ORG-CMC/puppet-core',
  :ref => 'v16.4.0'
mod 'puppet-fw',
  :git => 'git@ssh.dev.azure.com:v3/ConclusionMC/ORG-CMC/puppet-fw',
  :ref => 'v1.0.0'
mod 'cmc-puppetserver',
  :git => 'git@ssh.dev.azure.com:v3/ConclusionMC/ORG-CMC/puppet-puppetserver',
  :ref => 'v4.0.0'
