#!/usr/bin/env ruby
forge 'https://forgeapi.puppetlabs.com'

metadata

mod 'cmc-core',
  :git => 'https://-svc-AzureDevOps_CMC:zqx2rcuqfevkzwkqidgnnbuoixc26vsxsyhuzycumgqsdoehy5bq@dev.azure.com/ConclusionMC/ORG-CMC/_git/puppet-core',
  :ref => 'v18.29.2'
mod 'cmc-postfix',
  :git => 'https://-svc-AzureDevOps_CMC:zqx2rcuqfevkzwkqidgnnbuoixc26vsxsyhuzycumgqsdoehy5bq@dev.azure.com/ConclusionMC/ORG-CMC/_git/puppet-postfix',
  :ref => 'v2.0.0'
mod 'puppet-fw',
  :git => 'https://-svc-AzureDevOps_CMC:zqx2rcuqfevkzwkqidgnnbuoixc26vsxsyhuzycumgqsdoehy5bq@dev.azure.com/ConclusionMC/ORG-CMC/_git/puppet-fw',
  :ref => 'v1.1.5'
