#!/usr/bin/env ruby

forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-lvm', '0.7.0'
mod 'puppetlabs-stdlib', '4.25.0'
mod 'puppetlabs-firewall', '1.11.0'
mod 'puppet-selinux', '1.5.1'
mod 'puppetlabs-postgresql', '5.12.1'
mod 'puppet-zabbix', '6.7.0'
